config/routes.rb
Rails.application.routes.draw do
  root "cocktails#home"
  resources :cocktails, only: [:index, :create, :new, :show] do
    resources :doses, only: [:create, :destroy, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  layout "home", only: [:home]
  before_action :set_cocktail, only: [:show]
  def index
    @cocktails = Cocktail.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/new'
    end
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
  end

  def home
    @cocktails = Cocktail.all
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(params[:cocktail_id])
  end

  def index
    redirect_to "cocktail/show"
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/home.html.erb
<div class="page" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path "banner.jpg" %>)">
<div class="header">

 <div class="logo-banner">
    <%= image_tag "salad.png", class: "avatar" %>
  </div>
  <div class="sign-up">
    <a href="#" class="header-element"> Log In </a>
    <a href="#" class="header-element"> Sign Up </a>
  </div>
</div>
  <div class="banner">
    <div class="content-banner">
      <h1>Create and Find best cocktails</h1>
      <div class="content-search-bar">
        <div class="row">
          <form action="#" class="form-inline form-skel">
              <div class="form-group">
                <input type="text" name="" placeholder="Bloody mary">
              </div>
              <input type="submit" name="" class="button button-primary" value="Search">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="icon-container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="icon-content">
          <%= image_tag "globe.png" %>
             <h2>Discover new drinks</h2>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="icon-content">
          <%= image_tag "dollar.png" %>
          <h2>Make money</h2>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="icon-content">
          <%= image_tag "beer.png" %>
          <h2>Enjoy</h2>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="icon-content">
          <%= image_tag "heart.png" %>
          <h2>Share and love</h2>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/cards" %>

<%= render "shared/footer" %>

app/views/cocktails/index.html.erb
<%= render "shared/cards" %>

app/views/cocktails/new.html.erb
<div class="banner-show" style="background-image: url('<%= cl_image_path "jixeppgdpp3dzrdnu77d.jpg"%>')">

</div>
<div class="wrap-grey">
  <div class="container">
  <h2 id="form-h2-new">Create new cocktail</h2>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= simple_form_for @cocktail, html: {class: 'my-form'} do |f| %>
          <%= f.input :name, label_html: { class: 'form_label' }, label: 'Name*', error: 'Name can not be blank', hint: false, input_html: { class: 'my-form' }, :error_html => { :class => "name_error"} %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit, class: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner-show" style="background-image: url(<%= cl_image_path @cocktail.photo? ? @cocktail.photo : "lkgaqzb9hc9garraymlm.jpg" %>)">

</div>
<div class="wrap-grey">
  <div class="container">
   <h2 id="header-form"> <%= @cocktail.name %> </h2>

  <% if @cocktail.doses %>
    <h3 id="h3-form"> Recipe </h3>
    <div class="row">
        <div class="recipe-content">
          <% @cocktail.doses.each do |dose| %>
            <div class="col-xs-2 col-xs-offset-4">
              <p><i class="fa fa-square square-list" aria-hidden="true"></i> <%= dose.description %> </p>
            </div>
            <div class="col-xs-4">
               <p><%= dose.ingredient.name %> <i class="fa fa-glass" aria-hidden="true"></i> <%= link_to "Delete", cocktail_dose_path(@cocktail, dose), method: :delete, class: "delete-btn", data: {confirm: "Are you sure?"}  %> </p>
            </div>
          <% end %>
        </div>
    </div>
  <% end %>
  <h3 id="h3-form"> Add more ingredients </h3>
  <div class="row">
    <%= simple_form_for [@cocktail, @dose], html: { class: 'my-form' } do |f| %>
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="">
      <%= f.input :description, label_html: { class: 'form_label' }, label: 'Description*', error: 'Description can not be blank', hint: false, input_html: { class: 'my-form' }, :error_html => { :class => "name_error"} %>
    </div>
    <div class="">
      <%= f.association :ingredient, label_html: { class: 'form_label' }, label: "Ingredients*", prompt: "Select", input_html: { class: 'my-form form-style' }, error: 'Ingredients can not be blank', :error_html => { :class => "name_error"} %>
    </div>
      <%= f.button :submit, class: "button" %>
  </div>
  <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_cards.html.erb
<div class="wrap">
  <div class="container">
      <h2 id="start">All cocktails</h2>
      <div class="row">
        <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-4">
          <%= link_to cocktail_path(cocktail) do  %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path cocktail.photo? ?  cocktail.photo : "lkgaqzb9hc9garraymlm.jpg" %>);">
              <div class="card-description">
                <h2> <%=  cocktail.name %> </h2>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      </div>
    <div class="my-btn">
      <%= link_to "New cocktail", new_cocktail_path  %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="wrap-grey-footer">
  <div class="container footer-container">
    <div class="footer-box">
      <div class="row">
        <div class="col-xs-3 flex-footer">
        <%= image_tag "salad.png", id: "footer-logo" %>
        </div>
        <div class="col-xs-6 col-xs-offset-3">
          <div class="list-footer">
            <ul>
              <li>
                <a href="#"> About </a>
              </li>
              <li>
                <a href="#"> Contact us</a>
              </li>
              <li>
                <a href="#"> Le Wagon </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="links-box">
      <div class="icon-content">
        <a href="#" class="hover-facebook scale-icon" ><i class="fa fa-facebook-square" aria-hidden="true"></i> <br> <p>Facebook</p></a>
      </div>
      <div class="icon-content">
        <a href="#" class="hover-twitter scale-icon" ><i class="fa fa-twitter-square" aria-hidden="true"></i> <br> <p>Twitter</p></a>
      </div>
      <div class="icon-content">
        <a href="#" class="hover-github scale-icon" ><i class="fa fa-github-square" aria-hidden="true"></i> <br> <p>Github</p></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "salad.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "All cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "alex.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>